name: Publish NuGet

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/FastTechFoodsOrder.Shared.csproj

      - name: Build
        run: dotnet build ./src/FastTechFoodsOrder.Shared.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ./src/FastTechFoodsOrder.Shared.csproj --configuration Release --no-build --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
